using System;
using System.Linq;
using System.Collections.Generic;
using NuGet.Frameworks;

namespace tests
{
    public class MethodInfoTest
    {
        [TestMethod]
        public void AddTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void StopTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void GetMethodsListTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}