using System;
using System.Linq;
using System.Collections.Generic;
using NuGet.Frameworks;

namespace tests
{
    public class ThreadInfoTest
    {
        [TestMethod]
        public void StartTracingMethodTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void StopTracingMethodTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void GetMethodsTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}