using System;
using System.Linq;
using System.Collections.Generic;
using NuGet.Frameworks;

namespace tests
{
    public class TracerTest
    {
        [TestMethod]
        public void GetTraceResultTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void StartTraceTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void StopTraceTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}