using System;
using System.Linq;
using System.Collections.Generic;
using NuGet.Frameworks;

namespace tests
{
    public class TraceResultTest
    {
        [TestMethod]
        public void StartTracingTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void StopTracingTest()
        {
            Assert.Fail("autogenerated");
        }

        [TestMethod]
        public void GetResultsTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}